### ISSUE TITLE
Fix custom bars on items

### ISSUE THREAD

**Issue by williewillus** [williewillus/botania-fabric-issues#10]
There might be an API in FAPI for this

If too hard, consider holding this off until 1.17 which definitely has vanilla API's for this

**Comment by Yoghurt4C** [comment]
pointer: https://github.com/shedaniel/cloth-api/blob/1.16.2/cloth-durability-bar-api-v1/src/main/java/me/shedaniel/cloth/mixin/durability/bar/MixinItemRenderer.java
