### ISSUE TITLE
Shard of Laputa doesn't pick up double tall grass properly

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#101]
![image](https://user-images.githubusercontent.com/16853086/138574413-59681930-cac2-409b-8553-7de5fdd7690c.png)

**Comment by CammiePone** [comment]
Scratch that, any double tall plant

![image](https://user-images.githubusercontent.com/16853086/138574530-feb434ba-5658-436d-83b0-3ff7109d14c6.png)

**Comment by williewillus** [comment]
this is a thing in forge too. Fixing it is just complicated tm so I've just been ignoring it for the past 6 years

**Comment by CammiePone** [comment]
Fair enough
