### ISSUE TITLE
Ring of chordata (and potentially other mana-consuming trinkets) do not consume mana but instead add mana into the user's tabet/rings

### ISSUE THREAD

**Issue by FizzBuzz3000** [williewillus/botania-fabric-issues#104]
title says all, only tested with the ring of chordata, will update this issue later on for other trinkets.

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/4dc6f22211809b49678c10bb1a817c081bd28848 on both 1.16 and 1.17
