### ISSUE TITLE
[1.16.3 alpha] Crashes on loading

### ISSUE THREAD

**Issue by FynnWaelsing** [williewillus/botania-fabric-issues#18]
Botania: Botania-1.16.3-410-FABRIC-SNAPSHOT.jar
Fabric API: [1.16.3] Fabric API 0.25.0 build 415
Curios: curios-fabric-0.0.10-1.16.3.jar
Patchouli: Patchouli-1.16.2-44-FABRIC.jar
Lib block: [1.16.2/1.16.3] 0.8.2

Crash log: https://pastebin.com/r8pSn49h

Doesn't even get to the Mojang loading screen.

**Comment by williewillus** [comment]
Get the latest fapi

**Comment by FynnWaelsing** [comment]
Got it, thanks!
