### ISSUE TITLE
[1.16.3 alpha] Petal Apothecary (and other recipes) Uncraftable

### ISSUE THREAD

**Issue by FynnWaelsing** [williewillus/botania-fabric-issues#19]
Botania: Botania-1.16.3-410-FABRIC-SNAPSHOT.jar
Fabric API: [1.16.4] Fabric API 0.26.3
Curios: curios-fabric-0.0.10-1.16.3.jar
Patchouli: Patchouli-1.16.2-44-FABRIC.jar
Lib block: [1.16.4] v0.8.4

Don't seem to be able to craft the petal apothecary. It's entry in the Lexica is also busted.

![image](https://user-images.githubusercontent.com/45303748/100281744-7c004a80-2f38-11eb-8dbb-832cdcb0316f.png)

![image](https://user-images.githubusercontent.com/45303748/100281802-8f131a80-2f38-11eb-9325-c0de86f3f324.png)

![image](https://user-images.githubusercontent.com/45303748/100281817-93d7ce80-2f38-11eb-867e-14897fa4042f.png)

**Comment by williewillus** [comment]
depends on #1 

broken recipes are due to usage of forge tags in some of them
