### ISSUE TITLE
botania shears aren't treated as shears

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#35]

**Comment by williewillus** [comment]
can you try again on trunk and detail exactly what scenarios this happens in? The datagens all use the fabric tool tags now.

**Comment by MoriyaShiine** [comment]
I tried using manasteel shears on leaves, grass, sheep, and tall mystical flowers. The tall mystical flowers drop fine, but the leaves and grass drop their non-shear drops despite having the correct breaking speed (leaves break instantly). Right clicking a sheep had no effect.

**Comment by williewillus** [comment]
this is a fabric thing unfortunately, it doesn't patch hardcoded checks of Items.SHEARS to the fabric tool tag

**Comment by MoriyaShiine** [comment]
should this be closed then

**Comment by coolsimulations** [comment]
I ran into this same problem developing my own shears with Fabric and found this GitHub issue. Fortunately, I found a temporary solution until Fabric adds their own implementation of it. If you want you can check it out here https://github.com/coolsimulations/SurvivalPlus/commit/9f4348a5bee2a1553696e499d71477b66fbd1bb8 I've tested it successfully with modded leaves (such as [Terrestria](https://www.curseforge.com/minecraft/mc-mods/terrestria)) that don't use the Fabric Shears tag in their Loot Tables, too.

**Comment by MoriyaShiine** [comment]
Tested this again, none of it works except for tall mystical flowers and the elementium shears' aoe function
