### ISSUE TITLE
Conflict with Chest Cavity on World Load

### ISSUE THREAD

**Issue by budgej** [williewillus/botania-fabric-issues#37]
Minecraft 1.16.3
Fabric Loader 0.10.8
Fabric API 1.16.4-0.27.1
Curios API 1.16.3-0.0.10
Patchouli 1.16.2-44
Libblockattributes 1.16.4-0.8.4
Botania 1.16.3-410
Chest Cavity 1.16.3-2.0.0 (and same results with latest 1.16.4-2.2.2)

Steps to reproduce:  Create or load a single player world
Result:  Immediately see "Saving World" and game closes
Log:  https://pastebin.com/Dpw4keQ2 (line 188)

**Comment by williewillus** [comment]
ModifyDropsAPI is overwriting an entire method in its mixin

https://github.com/Tigereye504/modify-drops-api/blob/master/src/main/java/net/tigereye/modifydropsapi/mixin/LootTableGenerateLootMixin.java#L17

This is highly incompatible with other mods that use normal injects, like Botania, so I would recommend they not do that. We are using the more compatible mechanism here, so I don't think it's a Botania issue
