### ISSUE TITLE
Server Fails to Launch

### ISSUE THREAD

**Issue by budgej** [williewillus/botania-fabric-issues#38]
Minecraft 1.16.3
Fabric Loader 0.10.8
Fabric API 1.16.4-0.27.1
Curios API 1.16.3-0.0.10
Patchouli 1.16.2-44
Libblockattributes 1.16.4-0.8.4
Botania 1.16.3-410

Steps to reproduce:  Start the server
Result:  Crashes with no class error class 310
Log:  https://pastebin.com/0eQjvjQf

**Comment by williewillus** [comment]
ModifyDropsAPI is overwriting an entire method in its mixin

https://github.com/Tigereye504/modify-drops-api/blob/master/src/main/java/net/tigereye/modifydropsapi/mixin/LootTableGenerateLootMixin.java#L17

This is highly incompatible with other mods that use normal injects, like Botania, so I would recommend they *not* do that. We are using the more compatible mechanism here, so I don't think it's a Botania issue

**Comment by williewillus** [comment]
wooops, commented on the wrong issue. this server crash is fixed in the next build
