### ISSUE TITLE
Server Crash with Mana Spreader

### ISSUE THREAD

**Issue by budgej** [williewillus/botania-fabric-issues#41]
Minecraft 1.16.4
Fabric 0.10.8
Fabric API 1.16.4-0.27.1
Curios 1.16.3-0.0.10
Patchouli 1.16.4-48
Lib Block Attributes 1.16.4-0.8.4
Botania 1.16.4-411 Fabric
[crash-2020-12-29_18.15.46-server.txt](https://github.com/williewillus/botania-fabric-issues/files/5752527/crash-2020-12-29_18.15.46-server.txt)

Server crashes when mana spreader attempts to place mana in a mana pool.  No Class Defined:  class_638.  Only happens on dedicated, no crash in single player.

**Comment by williewillus** [comment]
fixed in trunk already, rebuild the mod
