### ISSUE TITLE
Mod particles display through blocks when an item pickup animation is playing

### ISSUE THREAD

**Issue by quat1024** [williewillus/botania-fabric-issues#48]
Noticed this on the botania-fabric testing server (might be a crossmod thing, then)

But if you pick up an item, the Pure Daisy particles appear through blocks during the duration of the item pickup. Same for mana burst particles.

**Comment by williewillus** [comment]
does it happen in forg?

**Comment by MoriyaShiine** [comment]
This doesn't happen any more
