### ISSUE TITLE
If you try to feed more than one item into a Crafty Crate via a Funnel, the Funnel eats the leftovers

### ISSUE THREAD

**Issue by Alwinfy** [williewillus/botania-fabric-issues#49]
https://cdn.discordapp.com/attachments/481719529337258004/799025083062026330/2021-01-13_15-19-31.mp4

**Comment by williewillus** [comment]
bug in forg too (though I think forge capabilities hide the problem there), fixed there.

https://github.com/VazkiiMods/Botania/commit/4d38967742d9d7fb67686c33171bdf296c2bef98
