### ISSUE TITLE
Exoflame Crash

### ISSUE THREAD

**Issue by Aelpecyem** [williewillus/botania-fabric-issues#50]
Exoflames will crash the game when supplied with mana

[crash-2021-01-16_12.25.46-server.txt](https://github.com/williewillus/botania-fabric-issues/files/5824287/crash-2021-01-16_12.25.46-server.txt)

Exoflame more like Crashdagame haha amirite gamers

**Comment by Hubry** [comment]
https://github.com/Vazkii/Botania/blob/4c39b77de3e430ce90920202851fc0b39faf79c2/build.gradle#L76-L80
Yeah Curios includes these. Except the block one which the exoflame expects :V

**Comment by williewillus** [comment]
wack

**Comment by williewillus** [comment]
https://github.com/Vazkii/Botania/commit/d69eff1651d080473b9baae1a4b2af11321bdd23
