### ISSUE TITLE
Crash with Canvas

### ISSUE THREAD

**Issue by LemmaEOF** [williewillus/botania-fabric-issues#52]
Minecraft 1.16.4
FAPI: 9.29.3+1.16
Canvas: 1.0.1267
Fabritania: 1.16.4-411-FABRIC-SNAPSHOT (self-compiled, available [here](https://cdn.discordapp.com/attachments/606229145298403328/800557947335081994/Botania-1.16.4-411-FABRIC-SNAPSHOT.jar))

[log](https://paste.ee/p/xzvfe)

When launching the game with both Canvas and Fabritania, the game will immediately crash due to a ClassCastException related to the Botania `ShaderWrappedRenderLayer` and the Canvas `MultiPhaseExt`. I'll report this to Canvas as well to see if there's anything grondag can do.

**Comment by Hubry** [comment]
No longer crashes according to Moriya, just some graphical issues.
