### ISSUE TITLE
Ring of Loki recurses without limit when breaking with the Shatterer

### ISSUE THREAD

**Issue by Alwinfy** [williewillus/botania-fabric-issues#54]
Sample crash log: https://pastebin.com/cbs8tEfA

Steps to reproduce:
1. Start a Superflat world
2. Grab a Shatterer and a Ring of Loki
3. Tap out a pattern of two adjacent blocks with the Loki Ring
4. Sneak and break a block
5. ???
6. Loss

**Comment by Alwinfy** [comment]
Almost Definitely The Cause: When breaking with the Shatterer, we simulate breaking the adjacent block too, which re-triggers the Ring of Loki, which makes us break the block 2 over, and so on ad infinitum

**Comment by Hubry** [comment]
I believe this was fixed on forge upstream? Probably not present anymore
