### ISSUE TITLE
Flugel Wing recipes don't work

### ISSUE THREAD

**Issue by Alwinfy** [williewillus/botania-fabric-issues#58]
![hmmm](https://user-images.githubusercontent.com/20421383/108601637-284ca400-7363-11eb-9fdf-50a6eb536920.png)

Tested on the GoG test server

**Comment by Hubry** [comment]
The nbt crafting lib uses `data` instead of `nbt` in jsons. [Some docs](https://mcwiki.siphalor.de/nbt-crafting/v2/#recipe-parts/results/)

**Comment by MoriyaShiine** [comment]
This works fine now
