### ISSUE TITLE
Rendering Tiny Potato crashes the game

### ISSUE THREAD

**Issue by Neubulae** [williewillus/botania-fabric-issues#60]
# Version Information
Fabric version:  0.11.3 + API 0.35.0
Botania version:  https://github.com/Vazkii/Botania/commit/cc11ed97cb98b4707e78810fbd5611b9b3067cd6

# Further Information
Link to crash log: https://paste.gg/p/anonymous/b2de8b7d25e541279c5b15e36d2ffd2e
Steps to reproduce:
1. Search for Tiny Potato on Creative

What I expected to happen:

A Tater.

What happened instead:

A Tatercide.

https://github.com/VazkiiMods/Botania/issues/3754

**Comment by williewillus** [comment]
doesn't seem to happen anymore
