### ISSUE TITLE
Rotten Heresy and Chocolate Advancement Broke

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#61]
The advancement you're supposed to get when you eat a Biscuit of Totality (Rotten Heresy and Chocolate) gets triggered whenever you eat any food item (tested with mutton, chicken, and apples).

**Comment by Hubry** [comment]
Ugh, yet another victim of the advancement format change. Really should migrate these to datagen

**Comment by CammiePone** [comment]
There will probably be more to come, as Moriya and I are going to try and 100% Botania in survival

Godspeed

**Comment by williewillus** [comment]
fixed now

**Comment by CammiePone** [comment]
Would this have also fixed the relics advancements? We _just_ got ahold of them and it gave all of them to us

**Comment by MoriyaShiine** [comment]
Should clarify that we only got 1 relic but all of the advancements, presumably locking us out of the rest
