### ISSUE TITLE
Pure Daisy Broke

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#63]
For whatever reason the Pure Daisy has a rotating, floating, orbiting render of itself going around itself. It's really bizarre.

![image](https://user-images.githubusercontent.com/16853086/132995260-ddb1b489-98a5-4531-953e-093f24cdfdf9.png)
![image](https://user-images.githubusercontent.com/16853086/132995262-80829c81-28cc-4c86-8908-851ea872256b.png)

**Comment by williewillus** [comment]
the floating flower rendering code is probably activating somehow

**Comment by williewillus** [comment]
fixed
