### ISSUE TITLE
Several blocks don't have mining levels or tools associated

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#64]
Tested with Livingwood and Livingrock, both are mined at the same rate with any tool and Livingrock can be harvested with a fist

**Comment by williewillus** [comment]
Everything should be properly assigned now

**Comment by Alasofia** [comment]
Separate but related issue: tools don't have a mining level attached.

**Comment by williewillus** [comment]
what do you mean? tools don't really have mining levels. Like are there blocks our picks can't break that they should be able to?

**Comment by Alasofia** [comment]
Yes. They're all equivalent to wooden pickaxes and can't break any blocks above mining level 0.

**Comment by Hubry** [comment]
@Alasofia try the latest commit, I added the tools to the proper fabric tool tags.

**Comment by Alasofia** [comment]
Will do now. Thank you!

**Comment by Alasofia** [comment]
Looks like that fixed it! I think, anyways. Will report back after a few days of playtesting :)
