### ISSUE TITLE
Flower crafting / Elven trading / Terrasteel crafting / probably more in Patchouli books doesn't render

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#65]
![2021-09-12_17 09 46](https://user-images.githubusercontent.com/45156123/133004334-fb636d42-255e-45a5-a045-bd4ca8ca40de.png)

**Comment by MoriyaShiine** [comment]
![2021-09-14_12 41 26](https://user-images.githubusercontent.com/45156123/133307168-94a35d39-fd5f-4da6-b8c9-98b50c627a33.png)

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/7191d39908655c7606922d5ec602dc636a189d98
