### ISSUE TITLE
Several sounds don't play

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#66]
Examples include the Wand of the Forest's "click" sound when toggling the mana pool, or the Petal Apothecary which doesn't make any sound when using an empty, water, or lava bucket on it

**Comment by williewillus** [comment]
try these in forge first pls

1. I'm like 70% sure this never dinged
2. I'm like 95% sure this never made a sound

**Comment by MoriyaShiine** [comment]
Looks like both of what you said is true, my b

I confused the mana pool and mana spreader toggle, the spreader makes the sound and not the pool. Apothecary doesn't make a sound in either version but I suggest adding the respective bucket sound since it's very jarring to not have any audio response
