### ISSUE TITLE
Crash with petal apothecaries

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#67]
I'm not exactly sure what happened but the test server has crashed 12 times over the last day and I only noticed the 12th one since nobody was online the first 11. It happened the instant I crafted an Endoflame, but it might have been a coincidence
[crash-2021-09-13_17.14.16-server.txt](https://github.com/williewillus/botania-fabric-issues/files/7157615/crash-2021-09-13_17.14.16-server.txt)

**Comment by Hubry** [comment]
TileAltar is the apothecary block entity, actually

**Comment by Hubry** [comment]
Vazkii/Botania@74d2ff5dd417e2ad01ec2fdb21194ae73ced842f
