### ISSUE TITLE
Cosmetics are broken in a lot of ways

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#68]
As seen in the video, the only thing working about cosmetics are the fact that you can combine them with other trinkets; they don't render when combined (and presumably when worn normally) and cannot be equipped without first being combined with another trinket. The sash doesn't render either, but that's a different issue

https://user-images.githubusercontent.com/45156123/133164203-3f6e30e9-d771-4d13-806b-e758ffc20e02.mp4

**Comment by Hubry** [comment]
Part 1 was a trivial tag addition, luckily I asked Emi about this ahead of time :V 
![really makes u think](https://user-images.githubusercontent.com/26120076/133169542-83659cae-bd02-401e-8b2b-bee9693db11e.png)

VazkiiMods/Botania@06d765e8e83b3ab25d037f1d74121019a5929c9c

**Comment by Hubry** [comment]
The broken renderer is caused by the proxy getting initialized after all the items are registered, it seems.

**Comment by williewillus** [comment]
Fixed the renderers. If anything specific is broken report them individually.
