### ISSUE TITLE
"A message from Elven Garde" doesn't have any text

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#70]
![2021-09-14_12 42 21](https://user-images.githubusercontent.com/45156123/133307278-9eae80ca-875b-4e46-ab05-82e8f974a31d.png)

**Comment by Hubry** [comment]
Looks like templates might just be broken?
Willie what did you do

**Comment by williewillus** [comment]
concen

**Comment by Hubry** [comment]
Wait I linked the wrong issue, #65 is the one

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/7191d39908655c7606922d5ec602dc636a189d98
