### ISSUE TITLE
Sprint-jumping off of a floating island flower kicks the player in multiplayer

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#71]
I haven't tested in singleplayer, but I was able to consistently kick me from the server by sprint-jumping off of a floating island flower, for some reason.

[log](https://pastebin.com/2wQizNdD)

**Comment by Hubry** [comment]
That's some nice client config access on servers. I suppose on Forge it just defaulted instead of crashing

**Comment by Hubry** [comment]
VazkiiMods/Botania@4f363b0eaba8f89e91bcfa56127f6d24460e793b
