### ISSUE TITLE
Tiny Potato east and west placement are inverted

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#72]
https://user-images.githubusercontent.com/45156123/133342686-ceb90477-4604-44b6-a53b-7b4ca518e86e.mp4

**Comment by MoriyaShiine** [comment]
It also appears that giving it an item is inverted on north, south, east, and west, but not top and bottom

**Comment by williewillus** [comment]
can you check forge, I think eutro mightve broken this before :P

**Comment by MoriyaShiine** [comment]
It works there

**Comment by williewillus** [comment]
fixed
