### ISSUE TITLE
Ghost item on ground when /give command for mana ring is used

### ISSUE THREAD

**Issue by Pretender8** [williewillus/botania-fabric-issues#73]
Using the command /give @a botania:mana_ring gives the item to players, but also generates a ghost item on the ground that cannot be picked up. It can be destroyed with fire, however.

**Comment by MoriyaShiine** [comment]
f in chat for the guy named A

**Comment by Hubry** [comment]
You should wrap your commands in `` `backticks!` `` to not ping anyone accidentally. (and you can use double backticks to show backticks like that)
Anyways.

The mixin hook aims to replicate what Forge does, but Forge replaces *all* instances of lifespan being 6000 with its hook, so fake items spawned by `/give` (for the effect of an item appearing on you) despawn after 1 tick anyways.
I'll just make the undespawnable items roll back to 0 age earlier and not roll back after ~5990 ticks of lifespan at all.

**Comment by Hubry** [comment]
VazkiiMods/Botania@9bb97545565bc0e3fdd92fb953f46fa484240ad9
The current injection was a non-composable ModifyConstant that has an existing mod targetting it already, so I am not sad about changing this.

**Comment by williewillus** [comment]
I'm going to be reworking this. We should just be calling the vanilla "setUnlimitedLifespan" flag (age = -32768 iirc).

The problem with that is it interferes with our logic that looks at age to determine whether flowers can pick things up. Once we separate that counter from vanilla's age flag, we can just do the straightforward and right thing.
