### ISSUE TITLE
Gaia Head doesn't render properly

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#74]
~~We summoned Gaia today, and while Gaia did reflect my skin as was hoped, but the shader that normally is applied didn't get applied.~~ This one is fixed already apparently, so forget that

On top of that, the Gaia Head wasn't rendering at all.

Lastly, the pixies Gaia summons didn't seem to be doing anything in the fight. Not sure what was up with that.

**Comment by williewillus** [comment]
fixed
