### ISSUE TITLE
Ring of Odin health boost doesn't save

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#75]
When a server restarts, the ring of odin's health boost doesn't get saved, causing the player to start with only half their health.

**Comment by Hubry** [comment]
This has existed for multiple MC versions, and will probably need a workaround along the lines of "manually heal player on join"

**Comment by williewillus** [comment]
does/how does vanilla avoid this issue if you have health boosted armor e.g.?

**Comment by Hubry** [comment]
It doesn't avoid the issue, it works exactly the same.

**Comment by Hubry** [comment]
[MC-17876](https://bugs.mojang.com/browse/MC-17876) is the vanilla issue. Maybe we should just mark this as wontfix idk

**Comment by williewillus** [comment]
yeah that's probably the job of another bug fixer mod if any

**Comment by CammiePone** [comment]
Ahh, alright. Mojank strikes again :despair:

I'll go ahead and close this then, since it's not a Botania problem specifically. Maybe I'll look into making a fix for it, since that seems to be what I'm good at doing. Solving Vanilla's problems for them
