### ISSUE TITLE
Sparks don't stay on top of mana pools

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#77]
Something in the last few commits caused sparks to no longer stay on mana pools. They just instantly break.

**Comment by williewillus** [comment]
@Alwinfy I think this is caused by https://github.com/VazkiiMods/Botania/commit/c979962682efb76ddb6ce10721182ac9a7c3bf18

Reverting locally fixed it for me. Could you take a look?

**Comment by Hubry** [comment]
Looks like the faulty method is the new impl of `getAttachPos()`?

**Comment by Hubry** [comment]
So Alwinfy used `getPositionUnderneath` when the PR was targetting 1.16, but accidentally changed the target to the method called `getOnPosition` when updating the PR.
The Mojang names of these two methods are `getBlockPosBelowThatAffectsMyMovement` and `getOnPos` on mojmap.

Anyways, VazkiiMods/Botania@018a4faf7360cf943c0a87ca004fe34f434c86d2
