### ISSUE TITLE
Getting one gaia relic gives all relic advancements

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#79]
This locks you out of getting all the other ones as well, unless you remove your advancements from you. We also mentioned this is another issue, but I decided it would be a good idea to make it its own issue report.

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/compare/3835af698ded009fe35368441a9622dad1d72ae0...056215fd55bff76cfdefbee8b09df975a2e0f24f
