### ISSUE TITLE
Replace FuzzyNBTIngredient and usages with NBTCrafting library

### ISSUE THREAD

**Issue by williewillus** [williewillus/botania-fabric-issues#8]

**Comment by Hubry** [comment]
Instead of pulling this lib I went and replaced the one remaining usage in crafting (we got rid of the laputa upgrades a while ago) with a custom recipe type only targetting water bottles.
https://github.com/VazkiiMods/Botania/commit/cd5244759952c25ecb111b681d929d2d555c84b8
