### ISSUE TITLE
Mana detector sends a signal even if no mana burst is connecting

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#81]
forge:

https://user-images.githubusercontent.com/45156123/134935839-8fa09753-36a9-41ad-902d-475c17276381.mp4

fabric:

https://user-images.githubusercontent.com/45156123/134935869-f6752dbf-e17d-4ac0-8989-15e06ef846e2.mp4

**Comment by Hubry** [comment]
smells like it doesn't check if it is just simulated

**Comment by Hubry** [comment]
VazkiiMods/Botania@062faf9d3f70d90588d67db7a282e4f8b27812e5
