### ISSUE TITLE
Abstruse platform doesn't render disguised blocks with Sodium

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#82]
without sodium (uses glass to showcase #4)

![2021-09-27_10 44 05](https://user-images.githubusercontent.com/45156123/134941281-b50bf140-e8a3-4e67-938d-77e141b328c2.png)

with sodium:

![2021-09-27_10 45 06](https://user-images.githubusercontent.com/45156123/134941395-6c55a521-c99c-4df2-b823-180db58a4d59.png)

**Comment by williewillus** [comment]
sodium doesn't support frapi which the platform needs

**Comment by MoriyaShiine** [comment]
Oic, close then?
