### ISSUE TITLE
Trying to craft Influence Lens with a Mana Blaster crashes client

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#83]
Works fine putting it on a Mana Spreader

[crash-2021-09-27_10.52.22-client.txt](https://github.com/williewillus/botania-fabric-issues/files/7237676/crash-2021-09-27_10.52.22-client.txt)

**Comment by Hubry** [comment]
Influence lens has a missing item color, it seems
VazkiiMods/Botania@53201d927cc294dbc3305fbb213f50522b8deb9b
