### ISSUE TITLE
Standing inside of a Spectral Platform has weird x-ray effect

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#84]
forge:
![2021-09-27_11 00 45](https://user-images.githubusercontent.com/45156123/134944125-58a20065-4d2e-4674-8cd9-ba59d31049c8.png)

fabric:
![2021-09-27_11 01 00](https://user-images.githubusercontent.com/45156123/134944209-fda88d6e-ce99-490c-94b4-58d01832e153.png)

**Comment by Hubry** [comment]
Seems like it got fixed, probably by https://github.com/VazkiiMods/Botania/commit/a4b29c4271357bd978e2443b65d2b00d08acfcf5
