### ISSUE TITLE
Spreader Turnable doesn't turn the tables

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#85]
forg
https://user-images.githubusercontent.com/45156123/135327339-202a8cf0-262e-41a7-a6e3-65be5d3981f5.mp4

fabik
https://user-images.githubusercontent.com/45156123/135327410-4ae57821-b9da-4ca7-ac99-f2382d0b5e86.mp4

**Comment by williewillus** [comment]
VazkiiMods/Botania@bd53385bf
