### ISSUE TITLE
Picking up an item stops all botania particle effects

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#87]
I don't know how I missed this until now, but picking up an item stops all of botania's particle effects. Tested with the things in the video, terra blade particles, and terrasteel crafting, so it's safe to assume all mod particles are affected

https://user-images.githubusercontent.com/45156123/135635828-cdd8049a-c39b-4dc3-8427-b3d736b03673.mp4

**Comment by quat1024** [comment]
I guess this is the opposite of #48

**Comment by williewillus** [comment]
I have no idea why this happens, probably some sort of state leak. But I'm pretty sure we set/restore all our state properly?

**Comment by quat1024** [comment]
For what it's worth, this doesn't happen with Canvas 🤔

**Comment by Hubry** [comment]
Worked around in https://github.com/VazkiiMods/Botania/commit/e3c636a88a79c323090b17a423a7a72a6f629220,
then properly fixed in https://github.com/VazkiiMods/Botania/commit/8525982f94807e58763307dc0c2a60fbd194d45c.
