### ISSUE TITLE
Livingwood avatar model broken

### ISSUE THREAD

**Issue by artemisSystem** [williewillus/botania-fabric-issues#89]
![2021-10-08_21 09 23](https://user-images.githubusercontent.com/39034386/136620220-b9ec9ccd-0be3-4a21-9347-59d2211f9f4c.png)
HOW
(The right arm looks like it's 2 blocks off and rotated incorrectly)

**Comment by williewillus** [comment]
fixed already, try latest build

**Comment by artemisSystem** [comment]
Oops forgot i wasn't on latest, sorry
