### ISSUE TITLE
Trinket Case Doesn't Allow You To Swap Trinkets

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#91]
You're unable to swap trinkets within the Trinket Case screen, and according to Moriya this is not intended behaviour

![image](https://user-images.githubusercontent.com/16853086/137533268-44cdcf94-3ebf-4aa1-a4b2-f26c0c9ec8a7.png)

**Comment by Hubry** [comment]
I dont think it works like this even on 1.16 Forge

**Comment by CammiePone** [comment]
Ah nvm then
