### ISSUE TITLE
Livingwood Avatar Doesn't Sync to Other Players

### ISSUE THREAD

**Issue by CammiePone** [williewillus/botania-fabric-issues#93]
When you give a Livingwood Avatar a rod, it doesn't tell other players around it that is has a rod in its hand until it's updated with mana. This also applies to when a rod is taken from a Livingwood Avatar, causing players to be able to receive phantom rods when they right click a Livingwood Avatar.

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/7c2c2ddb84906cec827fb0e073c567137b56ef37 should fix it? Idk? I am too lazy to set up 2 clients to reproduce this.
