### ISSUE TITLE
Trying to load Orechid REI stuff fails on servers, works fine on singleplayer

### ISSUE THREAD

**Issue by MoriyaShiine** [williewillus/botania-fabric-issues#97]
https://gist.github.com/MoriyaShiine/96d3660ee6c3c39a40830b81528630b4

**Comment by Hubry** [comment]
ugh

**Comment by williewillus** [comment]
pls you know better than to dump giant logspam directly into an issue, paste it please.

**Comment by MoriyaShiine** [comment]
I've been doing homework all day so my brain is kill, fixed lol (pastebin immediately deletes it so sorry for file)

**Comment by Hubry** [comment]
https://gist.github.com >>>> pastebin

**Comment by Hubry** [comment]
https://github.com/VazkiiMods/Botania/commit/57efacde43aa28317597c649c4c4d5e2b852a0bd
