### ISSUE TITLE
Mana Enchanter doesnt seem to work.

### ISSUE THREAD

**Issue by frikinjay** [williewillus/botania-fabric-issues#99]
Using Botania-1.17.1-420-FABRIC-SNAPSHOT.jar

Multiblock builds, the enchnater is being provided mana, takes item, I drop a book next to it but nothing happens when right clicking the enchanter with the wand.

**Comment by MoriyaShiine** [comment]
What commit are you on? It worked fine on the test server

**Comment by frikinjay** [comment]
The most recent one, i compiled it a couple hours ago.

**Comment by MoriyaShiine** [comment]
Works fine for me as of https://github.com/VazkiiMods/Botania/commit/8e8f0afe19b91272c5158ee161233d6c45c7aec6

https://user-images.githubusercontent.com/45156123/138202331-fb6ff2c9-1a7b-4255-bf7d-4282a68e199b.mp4

**Comment by frikinjay** [comment]
Could be one of these mods conflicting is my best guess, in the video below is what i mentioned above.

![image](https://user-images.githubusercontent.com/88995340/138205771-87cf8a86-ea81-40d8-bed0-3b51c4cf98fa.png)


https://user-images.githubusercontent.com/88995340/138205651-10280f7e-165d-452e-af7d-78a57c591886.mp4

**Comment by MoriyaShiine** [comment]
thocc

Maybe no enchant cap is making the cost too high?

**Comment by frikinjay** [comment]
From what i figure by talking to the dev and looking at what the mod does it just removes the cap and tweaks the anvil and does not mess with the cost calc. Is the enchanter dependent on vanilla anvil in any way?

**Comment by MoriyaShiine** [comment]
It doesn't look like it is. I would try without no enchant cap just to see if it's the cause, and if it is then pinpoint what exactly makes the enchanter not work

**Comment by frikinjay** [comment]
Doesnt seem to work even without NoEnchantCap

**Comment by frikinjay** [comment]
Ok I think i know what happened, my stupidity happened. I need to wake up for real. I was trying to apply fortune to a sword. Well it works with proper enchantments.
